name: Save Godot build cache
description: Save Godot build cache.
inputs:
  cache-name:
    description: The cache base name (job name by default).
    default: ${{ github.job }}
  cache-path:
    description: The SCons cache path.
    default: ${{ github.workspace }}/.scons_cache/

runs:
  using: composite
  steps:
    - name: Purge files before timestamp
      shell: sh
      run: godot/misc/scripts/purge_cache.py ${{ env.CACHE_TIMESTAMP }} "${{ inputs.cache-path }}"

    - name: Save SCons cache directory
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ inputs.cache-name }}|${{ github.ref_name }}|${{ github.sha }}
