using Microsoft.CodeAnalysis;

namespace MVLGenerator;

[Generator]
public class BuildInfoGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var provider = context.AnalyzerConfigOptionsProvider.Select((options, _) => {
			options.GlobalOptions.TryGetValue("build_property.InformationalVersion", out var version);
			options.GlobalOptions.TryGetValue("build_property.AppCommitHash", out var commitHash);
			options.GlobalOptions.TryGetValue("build_property.AppBuildTime", out var buildTime);

			return (
				Version: version ?? "0.0.0",
				CommitHash: commitHash ?? "Unknown",
				BuildTime: buildTime ?? "Unknown"
			);
		});

		context.RegisterSourceOutput(provider,
			(spc, info) => {
				var source = $$"""
							   // <auto-generated/>
							   using System;
							   using CSemVer;
							
							   public static class BuildInfo
							   {
							       public static readonly SVersion InformationalVersion = SVersion.Parse("{{info.Version}}");
							       public const string CommitHash = "{{info.CommitHash}}";
							       public static readonly DateTimeOffset BuildTime = DateTimeOffset.Parse("{{info.BuildTime}}");
							   }
							   """;
				spc.AddSource("BuildInfo.g.cs", source);
			});
	}
}
