using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MVLGenerator;

[Generator]
public class IconDictionaryGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
				"MVL.Utils.Attribute.IconDictionaryAttribute",
				predicate: static (node, _) => node is PropertyDeclarationSyntax,
				transform: GetTargetPropertySymbol)
			.Where(static m => m is not null);

		var combinedProvider = provider
			.Combine(context.AdditionalTextsProvider.Collect())
			.Combine(context.AnalyzerConfigOptionsProvider);

		var generationDataProvider = combinedProvider.Select(static (tuple, token) => {
			var ((propertyContext, additionalTexts), options) = tuple;
			var ctx = propertyContext!.Value;

			options.GlobalOptions.TryGetValue("build_property.projectdir", out var projectDir);
			var fullPath = Path.Combine(projectDir ?? "", ctx.JsonPath).Replace('\\', '/');

			var targetText = additionalTexts.FirstOrDefault(text =>
				text.Path.Replace('\\', '/').Equals(fullPath, StringComparison.OrdinalIgnoreCase));

			if (targetText == null)
				return (Context: ctx, Entries: ImmutableArray<KeyValuePair<string, string>>.Empty,
					Error: (string?)"FileNotFound");

			var jsonContent = targetText.GetText(token)?.ToString();
			if (string.IsNullOrWhiteSpace(jsonContent))
				return (Context: ctx, Entries: ImmutableArray<KeyValuePair<string, string>>.Empty, Error: (string?)"EmptyFile");

			try {
				var jsonOptions = new JsonSerializerOptions {
					AllowTrailingCommas = true,
					ReadCommentHandling = JsonCommentHandling.Skip
				};
				var dict = JsonSerializer.Deserialize<Dictionary<string, string>>(jsonContent!, jsonOptions);
				var entries = dict?.ToImmutableArray() ?? ImmutableArray<KeyValuePair<string, string>>.Empty;

				return (Context: ctx, Entries: entries, Error: null);
			} catch (JsonException ex) {
				return (Context: ctx, Entries: ImmutableArray<KeyValuePair<string, string>>.Empty, Error: (string?)ex.Message);
			}
		});
		context.RegisterSourceOutput(generationDataProvider, GenerateSource);
	}

	static private PropertySymbolContext? GetTargetPropertySymbol(
		GeneratorAttributeSyntaxContext context,
		CancellationToken token) {
		var propertySymbol = (IPropertySymbol)context.TargetSymbol;

		if (propertySymbol.Type is not INamedTypeSymbol { Name: "FrozenDictionary" } namedType ||
			namedType.TypeArguments.Length != 2 ||
			namedType.TypeArguments[0].SpecialType != SpecialType.System_String ||
			namedType.TypeArguments[1].SpecialType != SpecialType.System_String) {
			return null;
		}

		var attribute = context.Attributes.FirstOrDefault(attr => attr.AttributeClass?.Name == "IconDictionaryAttribute");
		if (attribute == null || attribute.ConstructorArguments.Length == 0) return null;

		var jsonPath = attribute.ConstructorArguments[0].Value as string;
		if (string.IsNullOrEmpty(jsonPath)) return null;

		return new PropertySymbolContext(
			propertySymbol.ContainingType.ContainingNamespace.ToDisplayString(),
			propertySymbol.ContainingType.Name,
			propertySymbol.Name,
			jsonPath!);
	}

	static private void GenerateSource(
		SourceProductionContext context,
		(PropertySymbolContext Context, ImmutableArray<KeyValuePair<string, string>> Entries, string? Error) data) {
		var (ctx, entries, error) = data;

		if (error != null) {
			if (error != "FileNotFound" && error != "EmptyFile") {
				context.ReportDiagnostic(Diagnostic.Create(
					new(
						"JD003",
						"JSON解析错误",
						$"JSON解析失败: {error}",
						"IconDictionary",
						DiagnosticSeverity.Error,
						true),
					Location.None));
			}

			return;
		}

		if (entries.IsDefaultOrEmpty) return;

		var fieldName = "_" + char.ToLower(ctx.PropertyName[0]) + ctx.PropertyName.Substring(1);
		var source = GenerateClassSource(ctx.NamespaceName, ctx.ClassName, ctx.PropertyName, fieldName, entries);

		context.AddSource($"{ctx.ClassName}.{ctx.PropertyName}.g.cs", SourceText.From(source, Encoding.UTF8));
	}

	static private string GenerateClassSource(
		string namespaceName,
		string className,
		string propertyName,
		string fieldName,
		ImmutableArray<KeyValuePair<string, string>> entries) {
		var entriesSource = string.Join(",\n\t\t",
			entries.Select(e =>
				$"{{ {SymbolDisplay.FormatLiteral(e.Key, true)}, {SymbolDisplay.FormatLiteral(e.Value, true)} }}"));

		return $$"""
				 // <auto-generated/>
				 #nullable enable
				 using System.Collections.Frozen;
				 using System.Collections.Generic;

				 namespace {{namespaceName}};

				 public partial class {{className}} {
				     private static readonly FrozenDictionary<string, string> {{fieldName}} = new Dictionary<string, string>() {
				         {{entriesSource}}
				     }.ToFrozenDictionary();

				     private static partial FrozenDictionary<string, string> {{propertyName}} { get => {{fieldName}}; }
				 }
				 """;
	}

	// 优化：使用 readonly record struct 提供基于值的相等性比较，这对增量缓存至关重要
	private readonly record struct PropertySymbolContext(
		string NamespaceName,
		string ClassName,
		string PropertyName,
		string JsonPath);
}