using System;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace MVLGenerator;

[Generator]
public class LicenseGenerator : IIncrementalGenerator {
	public void Initialize(IncrementalGeneratorInitializationContext context) {
		var allFiles = context.AdditionalTextsProvider.Collect();
		var compilationAndAllFiles = context.CompilationProvider.Combine(allFiles);

		context.RegisterSourceOutput(compilationAndAllFiles,
			static (spc, source) => {
				var entries = new StringBuilder();
				var filesByDirectory = source.Right.GroupBy(f => Path.GetDirectoryName(Path.GetFullPath(f.Path)));

				foreach (var group in filesByDirectory) {
					var licenseFile = group.FirstOrDefault(f =>
						Path.GetFileName(Path.GetFullPath(f.Path)).StartsWith("LICENSE", StringComparison.OrdinalIgnoreCase));

					var licenseContent = licenseFile?.GetText(spc.CancellationToken)?.ToString();
					if (licenseContent == null) {
						continue;
					}

					var finalContent = new StringBuilder();

					var websiteFile = group.FirstOrDefault(f =>
						Path.GetFileName(Path.GetFullPath(f.Path)).StartsWith("WEBSITE", StringComparison.OrdinalIgnoreCase));

					if (websiteFile != null) {
						var websiteUrl = websiteFile.GetText(spc.CancellationToken)?.ToString()?.Trim();
						if (!string.IsNullOrEmpty(websiteUrl)) {
							finalContent.AppendLine($"[color=#3c7fe1][url]{websiteUrl}[/url][/color]");
							finalContent.AppendLine();
						}
					}

					finalContent.Append(licenseContent);

					var escapedValue = finalContent.ToString().Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
					var directoryName = Path.GetFileName(group.Key);
					entries.AppendLine($"""        ("{directoryName}", "{escapedValue}"),""");
				}

				spc.AddSource($"Info.LICENSES.g.cs",
					SourceText.From($$"""
									  // <auto-generated/>
									  using System.Collections.Generic;

									  public static partial class Info
									  {
									      public static IReadOnlyList<(string, string)> LICENSES { get; } = [
									  {{entries.ToString().TrimEnd(',', '\r', '\n')}}
									      ];
									  }
									  """,
						Encoding.UTF8));
				
			});
	}
}